# Quick Start
# $ docker compose -f compose.talker.yaml up

services:

  master-sync-talker:
    build:
      context: .
      dockerfile: Dockerfile.multimaster
    depends_on: 
      husarnet-talker: { condition: service_healthy }
    network_mode: service:husarnet-talker
    tty: true
    environment:
      - ROS_IPV6=on
    command: rosrun fkie_master_sync master_sync _sync_hosts:=[listener-host,talker-host]

  master-discovery-talker:
    build:
      context: .
      dockerfile: Dockerfile.multimaster
    depends_on: 
      husarnet-talker: { condition: service_healthy }
    network_mode: service:husarnet-talker
    tty: true
    environment:
      - ROS_IPV6=on
    command: rosrun fkie_master_discovery master_discovery _check_host:=False

  ros-master-talker:
    image: ros:noetic-ros-core
    depends_on: 
      husarnet-talker: { condition: service_healthy }
    network_mode: service:husarnet-talker
    tty: true
    environment:
      - ROS_IPV6=on
    command: stdbuf -o L roscore

  talker:
    build:
      context: .
      dockerfile: Dockerfile.chatter
    depends_on: 
      husarnet-talker: { condition: service_healthy }
    network_mode: service:husarnet-talker
    tty: true
    environment:
      - ROS_IPV6=on
      - ROS_MASTER_URI=http://talker-host:11311
      - ROS_HOSTNAME=talker-host
    command: rosrun roscpp_tutorials talker

  husarnet-talker:
    image: husarnet/husarnet-nightly:2022.09.29.3
    volumes:
      - /var/lib/husarnet
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0 
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - HOSTNAME=talker-host
      - JOINCODE
      - WAIT_HOSTNAMES=talker-host,listener-host
      # - HUSARNET_DEBUG=1